version: '3.8'
services:
  app:
    build: .
    container_name: face_recog_main
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - dataset_data:/app/dataset
      - uploads_data:/app/uploads
    restart: unless-stopped

  train:
    build: .
    container_name: face_recog_train
    volumes:
      - .:/app
      - dataset_data:/app/dataset
      - uploads_data:/app/uploads
    command: ["python", "train_model.py"]
    profiles: ["train"]

volumes:
  dataset_data:
  uploads_data:
